package com.ernadas.webstart;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

@Controller
public class PageController {
	
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private TrasosRepository trasos_rep;	
	
	@RequestMapping(path="/trasos", method={ RequestMethod.GET, RequestMethod.POST })
    public String trasos(
    		@RequestParam(name="pav", required=false, defaultValue="") String pav
    		, @RequestParam(name="atstumas_km", required=false, defaultValue="10") Double atstumas_km
    		, @RequestParam(name="sukilimas", required=false, defaultValue="0") Integer sukilimas
    		, @RequestParam(name="pildyti", required=false, defaultValue="nepildyti") String pildyti
    		, Model model 
    	) {
        model.addAttribute("lst", trasos_rep.findAll() );
        
        if ( pildyti.equals("papildyti") ) {
        	
        	Trasos trasa = new Trasos( pav, atstumas_km, sukilimas );
        	trasos_rep.save( trasa );
        }
        
        return "trasos";
    }	

}
